- hosts: localhost
  tasks:
    - name: Installs httpd web server
      action: yum name=httpd state=latest 
      notify:
        - start httpd

  handlers:
    - name: start httpd
      service: name=httpd state=started enabled=yes
